Update all.json
ArkaneNetwork/content-management pull request #11
Opened 2021-01-13 12:51 UTC by gerbert-vandenberghe

2021-01-14 15:28 UTC, alpa-coder requested changes

2021-01-14 15:28 UTC, alpa-coder commented on tokens/matic/mainnet/details/all.json
> +{"name":"GHOST","symbol":"GHST","address":"0x385Eeac5cB85A38A9a07A70c73e0a3271CfB54A7","decimals":18,"type":"ERC20"},
trailing comma

2021-01-14 15:29 UTC, alpa-coder commented on tokens/matic/mainnet/details/all.json
> +{"name":"GHOST","symbol":"GHST","address":"0x385Eeac5cB85A38A9a07A70c73e0a3271CfB54A7","decimals":18,"type":"ERC20"},
also lowercase

2021-01-21 09:42 UTC, gerbert-vandenberghe commented
@alpa-coder alles zou in orde moeten zijn, maar blijkbaar is er een conflicting file. Hoe los ik dit op?

2021-02-15 13:49 UTC, closed without merging